---
#host this the place where we say to execute the playbook
- hosts: all 
 # become this is used to  give permision of becoming sudo or add sudo to execute admin activity
  become: yes
 #task here we give installing uninstalling stoping and starting services 
  tasks:
  # the task name we want to do 
  - name: "instaling git"
 #here we used apt because we are executing this in ubuntu these change according to linux flaveor
    apt:
# name of package we want to insatll
      name: git
# state means what u want to do install or uninistall the app
      state: present