# we need 2 machines with 2 gb ram and 2 vcpus
# 



Vagrant.configure(2) do |config|
  config.vm.define "master" do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "k8smaster"
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2024"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  SHELL
#machine 2 (k8snode1) configurations
  config.vm.define "node1" do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "k8node1"
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2024"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update
  SHELL
end